name: "${name}"
main: "${group}.interestingfish.${name}"
version: "${version}"
api-version: "1.13"
authors: ["lazertester", "Puremin0rez"]
website: "https://github.com/Puremin0rez/InterestingFish"
description: "Allow your players to catch fish with style - adds fancy names, weights and catch information to caught fish. "
