name: "${project.name}"
main: "${project.groupId}.${project.artifactId}.${project.name}"
version: "${project.version}"
api-version: "1.13"
authors: ["lazertester", "Puremin0rez"]
website: "https://github.com/Puremin0rez/InterestingFish"
description: "InterestingFish, gives fishes names and weight."
